name: Copy React Build to Backend and Deploy
on:
  pull_request:
    types:
      - closed
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          rm package-lock.json
          npm install

      - name: Build Frontend
        run: npm run build

      - name: Move Static Files to Backend
        run: |
          mkdir -p backend/public
          npm run move-statics

      # Pasos para el deploy en Railway
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: npm run deploy -w backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
